exports.Sectors = [
  { Sector: "Basic Materials", Industries: "Agricultural Chemicals" },
  { Sector: "Basic Materials", Industries: "Agricultural Inputs" },
  { Sector: "Basic Materials", Industries: "Aluminum" },
  { Sector: "Basic Materials", Industries: "Building Materials" },
  { Sector: "Basic Materials", Industries: "Chemicals" },
  { Sector: "Basic Materials", Industries: "Chemicals - Major Diversified" },
  { Sector: "Basic Materials", Industries: "Coal" },
  { Sector: "Basic Materials", Industries: "Coking Coal" },
  { Sector: "Basic Materials", Industries: "Copper" },
  { Sector: "Basic Materials", Industries: "Gold" },
  { Sector: "Basic Materials", Industries: "Independent Oil & Gas" },
  { Sector: "Basic Materials", Industries: "Industrial Metals & Minerals" },
  { Sector: "Basic Materials", Industries: "Lumber & Wood Production" },
  { Sector: "Basic Materials", Industries: "Major Integrated Oil & Gas" },
  { Sector: "Basic Materials", Industries: "Nonmetallic Mineral Mining" },
  { Sector: "Basic Materials", Industries: "Oil & Gas Drilling & Exploration" },
  { Sector: "Basic Materials", Industries: "Oil & Gas Equipment & Services" },
  { Sector: "Basic Materials", Industries: "Oil & Gas Pipelines" },
  { Sector: "Basic Materials", Industries: "Oil & Gas Refining & Marketing" },
  { Sector: "Basic Materials", Industries: "Other Industrial Metals & Mining" },
  { Sector: "Basic Materials", Industries: "Other Precious Metals & Mining" },
  { Sector: "Basic Materials", Industries: "Paper & Paper Products" },
  { Sector: "Basic Materials", Industries: "Silver" },
  { Sector: "Basic Materials", Industries: "Specialty Chemicals" },
  { Sector: "Basic Materials", Industries: "Steel" },
  { Sector: "Basic Materials", Industries: "Steel & Iron" },
  { Sector: "Basic Materials", Industries: "Synthetics" },

  { Sector: "Communication Services", Industries: "Advertising Agencies" },
  { Sector: "Communication Services", Industries: "Broadcasting" },
  {
    Sector: "Communication Services",
    Industries: "Electronic Gaming & Multimedia"
  },
  { Sector: "Communication Services", Industries: "Entertainment" },
  {
    Sector: "Communication Services",
    Industries: "Internet Content & Information"
  },
  { Sector: "Communication Services", Industries: "Pay TV" },
  { Sector: "Communication Services", Industries: "Publishing" },
  { Sector: "Communication Services", Industries: "Telecom Services" },
  { Sector: "Conglomerates", Industries: "Conglomerates" },
  { Sector: "Consumer Cyclical", Industries: "Advertising Agencies" },
  { Sector: "Consumer Cyclical", Industries: "Apparel Manufacturing" },
  { Sector: "Consumer Cyclical", Industries: "Apparel Retail" },
  { Sector: "Consumer Cyclical", Industries: "Apparel Stores" },
  { Sector: "Consumer Cyclical", Industries: "Auto & Truck Dealerships" },
  { Sector: "Consumer Cyclical", Industries: "Auto Manufacturers" },
  { Sector: "Consumer Cyclical", Industries: "Auto Parts" },
  { Sector: "Consumer Cyclical", Industries: "Broadcasting - Radio" },
  { Sector: "Consumer Cyclical", Industries: "Broadcasting - TV" },
  { Sector: "Consumer Cyclical", Industries: "Department Stores" },
  { Sector: "Consumer Cyclical", Industries: "Footwear & Accessories" },
  {
    Sector: "Consumer Cyclical",
    Industries: "Furnishings, Fixtures & Appliances"
  },
  { Sector: "Consumer Cyclical", Industries: "Gambling" },
  { Sector: "Consumer Cyclical", Industries: "Home Furnishings & Fixtures" },
  { Sector: "Consumer Cyclical", Industries: "Home Improvement Retail" },
  { Sector: "Consumer Cyclical", Industries: "Home Improvement Stores" },
  { Sector: "Consumer Cyclical", Industries: "Internet Retail" },
  { Sector: "Consumer Cyclical", Industries: "Leisure" },
  { Sector: "Consumer Cyclical", Industries: "Lodging" },
  { Sector: "Consumer Cyclical", Industries: "Luxury Goods" },
  { Sector: "Consumer Cyclical", Industries: "Marketing Services" },
  { Sector: "Consumer Cyclical", Industries: "Media - Diversified" },
  { Sector: "Consumer Cyclical", Industries: "Packaging & Containers" },
  { Sector: "Consumer Cyclical", Industries: "Personal Services" },
  { Sector: "Consumer Cyclical", Industries: "Publishing" },
  { Sector: "Consumer Cyclical", Industries: "Recreational Vehicles" },
  { Sector: "Consumer Cyclical", Industries: "Residential Construction" },
  { Sector: "Consumer Cyclical", Industries: "Resorts & Casinos" },
  { Sector: "Consumer Cyclical", Industries: "Restaurants" },
  { Sector: "Consumer Cyclical", Industries: "Rubber & Plastics" },
  { Sector: "Consumer Cyclical", Industries: "Specialty Retail" },
  { Sector: "Consumer Cyclical", Industries: "Textile Manufacturing" },
  { Sector: "Consumer Cyclical", Industries: "Travel Services" },
  { Sector: "Consumer Defensive", Industries: "Beverages - Brewers" },
  { Sector: "Consumer Defensive", Industries: "Beverages - Soft Drinks" },
  {
    Sector: "Consumer Defensive",
    Industries: "Beverages - Wineries & Distilleries"
  },
  { Sector: "Consumer Defensive", Industries: "Beverages-Brewers" },
  { Sector: "Consumer Defensive", Industries: "Beverages-Non-Alcoholic" },
  {
    Sector: "Consumer Defensive",
    Industries: "Beverages-Wineries & Distilleries"
  },
  { Sector: "Consumer Defensive", Industries: "Confectioners" },
  { Sector: "Consumer Defensive", Industries: "Discount Stores" },
  { Sector: "Consumer Defensive", Industries: "Education & Training Services" },
  { Sector: "Consumer Defensive", Industries: "Farm Products" },
  { Sector: "Consumer Defensive", Industries: "Food Distribution" },
  { Sector: "Consumer Defensive", Industries: "Grocery Stores" },
  { Sector: "Consumer Defensive", Industries: "Household & Personal Products" },
  { Sector: "Consumer Defensive", Industries: "Packaged Foods" },
  { Sector: "Consumer Defensive", Industries: "Pharmaceutical Retailers" },
  { Sector: "Consumer Defensive", Industries: "Tobacco" },
  { Sector: "Consumer Goods ", Industries: "Appliances" },
  { Sector: "Consumer Goods ", Industries: "Auto Manufacturers - Major" },
  { Sector: "Consumer Goods ", Industries: "Auto Parts" },
  { Sector: "Consumer Goods ", Industries: "Beverages - Brewers" },
  { Sector: "Consumer Goods ", Industries: "Beverages - Soft Drinks" },
  {
    Sector: "Consumer Goods ",
    Industries: "Beverages - Wineries & Distillers"
  },
  { Sector: "Consumer Goods", Industries: "Business Equipment" },
  { Sector: "Consumer Goods", Industries: "Cigarettes" },
  { Sector: "Consumer Goods", Industries: "Cleaning Products" },
  { Sector: "Consumer Goods", Industries: "Confectioners" },
  { Sector: "Consumer Goods", Industries: "Dairy Products" },
  { Sector: "Consumer Goods", Industries: "Electronic Equipment" },
  { Sector: "Consumer Goods", Industries: "Farm Products" },
  { Sector: "Consumer Goods", Industries: "Food - Major Diversified" },
  { Sector: "Consumer Goods", Industries: "Home Furnishings & Fixtures" },
  { Sector: "Consumer Goods", Industries: "Housewares & Accessories" },
  { Sector: "Consumer Goods", Industries: "Meat Products" },
  { Sector: "Consumer Goods", Industries: "Office Supplies" },
  { Sector: "Consumer Goods", Industries: "Packaging & Containers" },
  { Sector: "Consumer Goods", Industries: "Paper & Paper Products" },
  { Sector: "Consumer Goods", Industries: "Personal Products" },
  {
    Sector: "Consumer Goods ",
    Industries: "Photographic Equipment & Supplies"
  },
  { Sector: "Consumer Goods", Industries: "Processed & Packaged Goods" },
  { Sector: "Consumer Goods", Industries: "Recreational Goods, Other" },
  { Sector: "Consumer Goods", Industries: "Recreational Vehicles" },
  { Sector: "Consumer Goods", Industries: "REIT - Retail" },
  { Sector: "Consumer Goods", Industries: "Rubber & Plastics" },
  { Sector: "Consumer Goods", Industries: "Sporting Goods" },
  { Sector: "Consumer Goods", Industries: "Textile - Apparel Clothing" },
  {
    Sector: "Consumer Goods",
    Industries: "Textile - Apparel Footwear & Accessories"
  },
  { Sector: "Consumer Goods ", Industries: "Tobacco Products, Other" },
  { Sector: "Consumer Goods ", Industries: "Toys & Games" },
  { Sector: "Consumer Goods ", Industries: "Trucks & Other Vehicles" },

  { Sector: "Energy", Industries: "Oil & Gas Drilling" },
  { Sector: "Energy", Industries: "Oil & Gas E&P" },
  { Sector: "Energy", Industries: "Oil & Gas Equipment & Services" },
  { Sector: "Energy", Industries: "Oil & Gas Integrated" },
  { Sector: "Energy", Industries: "Oil & Gas Midstream" },
  { Sector: "Energy", Industries: "Oil & Gas Refining & Marketing" },
  { Sector: "Energy", Industries: "Thermal Coal" },
  { Sector: "Energy", Industries: "Uranium" },
  { Sector: "Financial", Industries: "Accident & Health Insurance" },
  { Sector: "Financial", Industries: "Asset Management" },
  { Sector: "Financial", Industries: "Closed-End Fund - Debt" },
  { Sector: "Financial", Industries: "Closed-End Fund - Equity" },
  { Sector: "Financial", Industries: "Closed-End Fund - Foreign" },
  { Sector: "Financial", Industries: "Credit Services" },
  { Sector: "Financial", Industries: "Diversified Investments" },
  { Sector: "Financial", Industries: "Foreign Money Center Banks" },
  { Sector: "Financial", Industries: "Foreign Regional Banks" },
  { Sector: "Financial", Industries: "Insurance Brokers" },
  { Sector: "Financial", Industries: "Investment Brokerage - National" },
  { Sector: "Financial", Industries: "Investment Brokerage - Regional" },
  { Sector: "Financial", Industries: "Life Insurance" },
  { Sector: "Financial", Industries: "Money Center Banks" },
  { Sector: "Financial", Industries: "Mortgage Investment" },
  { Sector: "Financial", Industries: "Property & Casualty Insurance" },
  { Sector: "Financial", Industries: "Property Management" },
  { Sector: "Financial", Industries: "Real Estate Development" },
  { Sector: "Financial", Industries: "Regional - Mid-Atlantic Banks" },
  { Sector: "Financial", Industries: "Regional - Midwest Banks" },
  { Sector: "Financial", Industries: "Regional - Northeast Banks" },
  { Sector: "Financial", Industries: "Regional - Pacific Banks" },
  { Sector: "Financial", Industries: "Regional - Southeast Banks" },
  { Sector: "Financial", Industries: "Regional - Southwest  Banks" },
  { Sector: "Financial", Industries: "REIT - Diversified" },
  { Sector: "Financial", Industries: "REIT - Healthcare Facilities" },
  { Sector: "Financial", Industries: "REIT - Hotel/Motel" },
  { Sector: "Financial", Industries: "REIT - Industrial" },
  { Sector: "Financial", Industries: "REIT - Office" },
  { Sector: "Financial", Industries: "REIT - Residential" },
  { Sector: "Financial", Industries: "REIT - Retail" },
  { Sector: "Financial", Industries: "Savings & Loans" },
  { Sector: "Financial", Industries: "Surety & Title Insurance" },
  { Sector: "Financial Services", Industries: "Asset Management" },
  { Sector: "Financial Services", Industries: "Banks - Global" },
  { Sector: "Financial Services", Industries: "Banks - Regional - Africa" },
  { Sector: "Financial Services", Industries: "Banks - Regional - Asia" },
  { Sector: "Financial Services", Industries: "Banks - Regional - Australia" },
  { Sector: "Financial Services", Industries: "Banks - Regional - Canada" },
  { Sector: "Financial Services", Industries: "Banks - Regional - Europe" },
  {
    Sector: "Financial Services",
    Industries: "Banks - Regional - Latin America"
  },
  { Sector: "Financial Services", Industries: "Banks - Regional - US" },
  { Sector: "Financial Services", Industries: "Banks-Diversified" },
  { Sector: "Financial Services", Industries: "Banks-Regional" },
  { Sector: "Financial Services", Industries: "Capital Markets" },
  { Sector: "Financial Services", Industries: "Credit Services" },
  { Sector: "Financial Services", Industries: "Financial Conglomerates" },
  {
    Sector: "Financial Services",
    Industries: "Financial Data & Stock Exchanges"
  },
  { Sector: "Financial Services", Industries: "Financial Exchanges" },
  { Sector: "Financial Services", Industries: "Insurance - Diversified" },
  { Sector: "Financial Services", Industries: "Insurance - Life" },
  {
    Sector: "Financial Services",
    Industries: "Insurance - Property & Casualty"
  },
  { Sector: "Financial Services", Industries: "Insurance - Reinsurance" },
  { Sector: "Financial Services", Industries: "Insurance - Specialty" },
  { Sector: "Financial Services", Industries: "Insurance Brokers" },
  { Sector: "Financial Services", Industries: "Insurance-Diversified" },
  { Sector: "Financial Services", Industries: "Insurance-Life" },
  { Sector: "Financial Services", Industries: "Insurance-Property & Casualty" },
  { Sector: "Financial Services", Industries: "Insurance-Reinsurance" },
  { Sector: "Financial Services", Industries: "Insurance-Specialty" },
  { Sector: "Financial Services", Industries: "Mortgage Finance" },
  { Sector: "Financial Services", Industries: "Savings & Cooperative Banks" },
  { Sector: "Financial Services", Industries: "Shell Companies" },
  { Sector: "Financial Services", Industries: "Specialty Finance" },

  { Sector: "Healthcare", Industrie: "Biotechnology" },
  { Sector: "Healthcare", Industrie: "Diagnostic Substances" },
  { Sector: "Healthcare", Industrie: "Diagnostics & Research" },
  { Sector: "Healthcare", Industrie: "Drug Delivery" },
  { Sector: "Healthcare", Industrie: "Drug Manufacturers - Major" },
  { Sector: "Healthcare", Industrie: "Drug Manufacturers - Other" },
  {
    Sector: "Healthcare",
    Industrie: "Drug Manufacturers - Specialty & Generic"
  },
  { Sector: "Healthcare", Industrie: "Drug Manufacturers-General" },
  { Sector: "Healthcare", Industrie: "Drug Manufacturers-Specialty & Generic" },
  { Sector: "Healthcare", Industrie: "Drug Related Products" },
  { Sector: "Healthcare", Industrie: "Drugs - Generic" },
  { Sector: "Healthcare", Industrie: "Health Care Plans" },
  { Sector: "Healthcare", Industrie: "Health Information Services" },
  { Sector: "Healthcare", Industrie: "Healthcare Plans" },
  { Sector: "Healthcare", Industrie: "Home Health Care" },
  { Sector: "Healthcare", Industrie: "Hospitals" },
  { Sector: "Healthcare", Industrie: "Long-Term Care Facilities" },
  { Sector: "Healthcare", Industrie: "Medical Appliances & Equipment" },
  { Sector: "Healthcare", Industrie: "Medical Care" },
  { Sector: "Healthcare", Industrie: "Medical Care Facilities" },
  { Sector: "Healthcare", Industrie: "Medical Devices" },
  { Sector: "Healthcare", Industrie: "Medical Distribution" },
  { Sector: "Healthcare", Industrie: "Medical Instruments & Supplies" },
  { Sector: "Healthcare", Industrie: "Medical Laboratories & Research" },
  { Sector: "Healthcare", Industrie: "Medical Practitioners" },
  { Sector: "Healthcare", Industrie: "Pharmaceutical Retailers" },
  { Sector: "Healthcare", Industrie: "Specialized Health Services" },
  {
    Sector: "Industrial Goods",
    Industries: "Aerospace/Defense - Major Diversified"
  },
  {
    Sector: "Industrial Goods",
    Industries: "Aerospace/Defense Products & Services"
  },
  { Sector: "Industrial Goods", Industries: "Cement" },
  { Sector: "Industrial Goods", Industries: "Diversified Machinery" },
  { Sector: "Industrial Goods", Industries: "Farm & Construction Machinery" },
  { Sector: "Industrial Goods", Industries: "General Building Materials" },
  { Sector: "Industrial Goods", Industries: "General Contractors" },
  { Sector: "Industrial Goods", Industries: "Heavy Construction" },
  { Sector: "Industrial Goods", Industries: "Industrial Electrical Equipment" },
  {
    Sector: "Industrial Goods",
    Industries: "Industrial Equipment & Components"
  },
  { Sector: "Industrial Goods", Industries: "Lumber, Wood Production" },
  { Sector: "Industrial Goods", Industries: "Machine Tools & Accessories" },
  { Sector: "Industrial Goods", Industries: "Manufactured Housing" },
  { Sector: "Industrial Goods", Industries: "Metal Fabrication" },
  { Sector: "Industrial Goods", Industries: "Pollution & Treatment Controls" },
  { Sector: "Industrial Goods", Industries: "Residential Construction" },
  { Sector: "Industrial Goods", Industries: "Small Tools & Accessories" },
  { Sector: "Industrial Goods", Industries: "Textile Industrial" },
  { Sector: "Industrial Goods", Industries: "Waste Management" },
  { Sector: "Industrials ", Industries: "Aerospace & Defense" },
  { Sector: "Industrials ", Industries: "Airlines" },
  { Sector: "Industrials ", Industries: "Airports & Air Services" },
  { Sector: "Industrials ", Industries: "Building Products & Equipment" },
  { Sector: "Industrials ", Industries: "Business Equipment" },
  { Sector: "Industrials ", Industries: "Business Equipment & Supplies" },
  { Sector: "Industrials ", Industries: "Business Services" },
  { Sector: "Industrials ", Industries: "Conglomerates" },
  { Sector: "Industrials ", Industries: "Consulting Services" },
  { Sector: "Industrials ", Industries: "Diversified Industrials" },
  { Sector: "Industrials ", Industries: "Electrical Equipment & Parts" },
  { Sector: "Industrials ", Industries: "Engineering & Construction" },
  { Sector: "Industrials ", Industries: "Farm & Construction Equipment" },
  { Sector: "Industrials ", Industries: "Farm & Heavy Construction Machinery" },
  { Sector: "Industrials ", Industries: "Industrial Distribution" },
  { Sector: "Industrials ", Industries: "Infrastructure Operations" },
  { Sector: "Industrials ", Industries: "Integrated Freight & Logistics" },
  { Sector: "Industrials ", Industries: "Integrated Shipping & Logistics" },
  { Sector: "Industrials ", Industries: "Marine Shipping" },
  { Sector: "Industrials ", Industries: "Metal Fabrication" },
  { Sector: "Industrials ", Industries: "Pollution & Treatment Controls" },
  { Sector: "Industrials ", Industries: "Railroads" },
  { Sector: "Industrials ", Industries: "Rental & Leasing Services" },
  { Sector: "Industrials ", Industries: "Security & Protection Services" },
  { Sector: "Industrials ", Industries: "Shipping & Ports" },
  { Sector: "Industrials ", Industries: "Specialty Business Services" },
  { Sector: "Industrials ", Industries: "Specialty Industrial Machinery" },
  { Sector: "Industrials ", Industries: "Staffing & Employment Services" },
  { Sector: "Industrials ", Industries: "Staffing & Outsourcing Services" },
  { Sector: "Industrials ", Industries: "Tools & Accessories" },
  { Sector: "Industrials ", Industries: "Truck Manufacturing" },
  { Sector: "Industrials ", Industries: "Trucking" },
  { Sector: "Industrials ", Industries: "Waste Management" },
  { Sector: "Other", Industries: "Other" },
  { Sector: "Real Estate", Industries: "Real Estate - General" },
  { Sector: "Real Estate", Industries: "Real Estate Services" },
  { Sector: "Real Estate", Industries: "Real Estate-Development" },
  { Sector: "Real Estate", Industries: "Real Estate-Diversified" },
  { Sector: "Real Estate", Industries: "REIT - Diversified" },
  { Sector: "Real Estate", Industries: "REIT - Healthcare Facilities" },
  { Sector: "Real Estate", Industries: "REIT - Hotel & Motel" },
  { Sector: "Real Estate", Industries: "REIT - Industrial" },
  { Sector: "Real Estate", Industries: "REIT - Office" },
  { Sector: "Real Estate", Industries: "REIT - Residential" },
  { Sector: "Real Estate", Industries: "REIT - Retail" },
  { Sector: "Real Estate", Industries: "REIT-Diversified" },
  { Sector: "Real Estate", Industries: "REIT-Healthcare Facilities" },
  { Sector: "Real Estate", Industries: "REIT-Hotel & Motel" },
  { Sector: "Real Estate", Industries: "REIT-Industrial" },
  { Sector: "Real Estate", Industries: "REIT-Mortgage" },
  { Sector: "Real Estate", Industries: "REIT-Office" },
  { Sector: "Real Estate", Industries: "REIT-Residential" },
  { Sector: "Real Estate", Industries: "REIT-Retail" },
  { Sector: "Real Estate", Industries: "REIT-Specialty" },
  { Sector: "Services", Industries: "Advertising Agencies" },
  { Sector: "Services", Industries: "Air Delivery & Freight Services" },
  { Sector: "Services", Industries: "Air Services, Other" },
  { Sector: "Services", Industries: "Apparel Stores" },
  { Sector: "Services", Industries: "Auto Dealerships" },
  { Sector: "Services", Industries: "Auto Parts Stores" },
  { Sector: "Services", Industries: "Auto Parts Wholesale" },
  { Sector: "Services", Industries: "Basic Materials Wholesale" },
  { Sector: "Services", Industries: "Broadcasting - Radio" },
  { Sector: "Services", Industries: "Broadcasting - TV" },
  { Sector: "Services", Industries: "Building Materials Wholesale" },
  { Sector: "Services", Industries: "Business Services" },
  { Sector: "Services", Industries: "Catalog & Mail Order Houses" },
  { Sector: "Services", Industries: "CATV Systems" },
  { Sector: "Services", Industries: "Computers Wholesale" },
  { Sector: "Services", Industries: "Consumer Services" },
  { Sector: "Services", Industries: "Department Stores" },
  { Sector: "Services", Industries: "Discount, Variety Stores" },
  { Sector: "Services", Industries: "Drug Stores" },
  { Sector: "Services", Industries: "Drugs Wholesale" },
  { Sector: "Services", Industries: "Education & Training Services" },
  { Sector: "Services", Industries: "Electronics Stores" },
  { Sector: "Services", Industries: "Electronics Wholesale" },
  { Sector: "Services", Industries: "Entertainment - Diversified" },
  { Sector: "Services", Industries: "Food Wholesale" },
  { Sector: "Services", Industries: "Gaming Activities" },
  { Sector: "Services", Industries: "General Entertainment" },
  { Sector: "Services", Industries: "Grocery Stores" },
  { Sector: "Services", Industries: "Home Furnishing Stores" },
  { Sector: "Services", Industries: "Home Improvement Stores" },
  { Sector: "Services", Industries: "Industrial Equipment Wholesale" },
  { Sector: "Services", Industries: "Information Technology Services" },
  { Sector: "Services", Industries: "Jewelry Stores" },
  { Sector: "Services", Industries: "Lodging" },
  { Sector: "Services", Industries: "Major Airlines" },
  { Sector: "Services", Industries: "Management Services" },
  { Sector: "Services", Industries: "Marketing Services" },
  { Sector: "Services", Industries: "Medical Equipment Wholesale" },
  { Sector: "Services", Industries: "Movie Production, Theaters" },
  { Sector: "Services", Industries: "Music & Video Stores" },
  { Sector: "Services", Industries: "Personal Services" },
  { Sector: "Services", Industries: "Publishing - Books" },
  { Sector: "Services", Industries: "Publishing - Newspapers" },
  { Sector: "Services", Industries: "Publishing - Periodicals" },
  { Sector: "Services", Industries: "Railroads" },
  { Sector: "Services", Industries: "Regional Airlines" },
  { Sector: "Services", Industries: "Rental & Leasing Services" },
  { Sector: "Services", Industries: "Research Services" },
  { Sector: "Services", Industries: "Resorts & Casinos" },
  { Sector: "Services", Industries: "Restaurants" },
  { Sector: "Services", Industries: "Security & Protection Services" },
  { Sector: "Services", Industries: "Shipping" },
  { Sector: "Services", Industries: "Specialty Eateries" },
  { Sector: "Services", Industries: "Specialty Retail, Other" },
  { Sector: "Services", Industries: "Sporting Activities" },
  { Sector: "Services", Industries: "Sporting Goods Stores" },
  { Sector: "Services", Industries: "Staffing & Outsourcing Services" },
  { Sector: "Services", Industries: "Technical Services" },
  { Sector: "Services", Industries: "Toy & Hobby Stores" },
  { Sector: "Services", Industries: "Trucking" },
  { Sector: "Services", Industries: "Wholesale, Other" },
  { Sector: "Technology", Industries: "Application Software" },
  { Sector: "Technology", Industries: "Business Software & Services" },
  { Sector: "Technology", Industries: "Communication Equipment" },
  { Sector: "Technology", Industries: "Computer Based Systems" },
  { Sector: "Technology", Industries: "Computer Distribution" },
  { Sector: "Technology", Industries: "Computer Hardware" },
  { Sector: "Technology", Industries: "Computer Peripherals" },
  { Sector: "Technology", Industries: "Computer Systems" },
  { Sector: "Technology", Industries: "Consumer Electronics" },
  { Sector: "Technology", Industries: "Contract Manufacturers" },
  { Sector: "Technology", Industries: "Data Storage" },
  { Sector: "Technology", Industries: "Data Storage Devices" },
  { Sector: "Technology", Industries: "Diversified Communication Services" },
  { Sector: "Technology", Industries: "Diversified Computer Systems" },
  { Sector: "Technology", Industries: "Diversified Electronics" },
  { Sector: "Technology", Industries: "Electronic Components" },
  { Sector: "Technology", Industries: "Electronic Gaming & Multimedia" },
  { Sector: "Technology", Industries: "Electronics & Computer Distribution" },
  { Sector: "Technology", Industries: "Electronics Distribution" },
  { Sector: "Technology", Industries: "Health Information Services" },
  { Sector: "Technology", Industries: "Healthcare Information Services" },
  { Sector: "Technology", Industries: "Information & Delivery Services" },
  { Sector: "Technology", Industries: "Information Technology Services" },
  { Sector: "Technology", Industries: "Internet Content & Information" },
  { Sector: "Technology", Industries: "Internet Information Providers" },
  { Sector: "Technology", Industries: "Internet Service Providers" },
  { Sector: "Technology", Industries: "Internet Software & Services" },
  { Sector: "Technology", Industries: "Long Distance Carriers" },
  { Sector: "Technology", Industries: "Multimedia & Graphics Software" },
  { Sector: "Technology", Industries: "Networking & Communication Devices" },
  { Sector: "Technology", Industries: "Personal Computers" },
  { Sector: "Technology", Industries: "Printed Circuit Boards" },
  { Sector: "Technology", Industries: "Processing Systems & Products" },
  { Sector: "Technology", Industries: "Scientific & Technical Instruments" },
  { Sector: "Technology", Industries: "Security Software & Services" },
  { Sector: "Technology", Industries: "Semiconductor - Broad Line" },
  { Sector: "Technology", Industries: "Semiconductor - Integrated Circuits" },
  { Sector: "Technology", Industries: "Semiconductor - Specialized" },
  { Sector: "Technology", Industries: "Semiconductor Equipment & Materials" },
  { Sector: "Technology", Industries: "Semiconductor Memory" },
  { Sector: "Technology", Industries: "Semiconductor- Memory Chips" },
  { Sector: "Technology", Industries: "Semiconductors" },
  { Sector: "Technology", Industries: "Software - Application" },
  { Sector: "Technology", Industries: "Software - Infrastructure" },
  { Sector: "Technology", Industries: "Software-Application" },
  { Sector: "Technology", Industries: "Software-Infrastructure" },
  { Sector: "Technology", Industries: "Solar" },
  { Sector: "Technology", Industries: "Technical & System Software" },
  { Sector: "Technology", Industries: "Telecom Services - Domestic" },
  { Sector: "Technology", Industries: "Telecom Services - Foreign" },
  { Sector: "Technology", Industries: "Wireless Communications" },
  { Sector: "Utilities", Industries: "Diversified Utilities" },
  { Sector: "Utilities", Industries: "Electric Utilities" },
  { Sector: "Utilities", Industries: "Foreign Utilities" },
  { Sector: "Utilities", Industries: "Gas Utilities" },
  { Sector: "Utilities", Industries: "Utilities - Diversified" },
  {
    Sector: "Utilities",
    Industries: "Utilities - Independent Power Producers"
  },
  { Sector: "Utilities", Industries: "Utilities - Regulated Electric" },
  { Sector: "Utilities", Industries: "Utilities - Regulated Gas" },
  { Sector: "Utilities", Industries: "Utilities - Regulated Water" },
  { Sector: "Utilities", Industries: "Utilities-Diversified" },
  { Sector: "Utilities", Industries: "Utilities-Independent Power Producers" },
  { Sector: "Utilities", Industries: "Utilities-Regulated Electric" },
  { Sector: "Utilities", Industries: "Utilities-Regulated Gas" },
  { Sector: "Utilities", Industries: "Utilities-Regulated Water" },
  { Sector: "Utilities", Industries: "Utilities-Renewable" },
  { Sector: "Utilities", Industries: "Water Utilities" }
];
